import Foundation

/// Reads build-time configuration injected via Secrets.xcconfig -> Info.plist.
enum AppConfig {
    static var supabaseURL: URL {
        guard
            let ref = Bundle.main.object(forInfoDictionaryKey: "SUPABASE_PROJECT_REF") as? String,
            !ref.isEmpty,
            let url = URL(string: "https://\(ref).supabase.co")
        else {
            fatalError("SUPABASE_PROJECT_REF is missing. Check Echo/Resources/Secrets.xcconfig.")
        }
        return url
    }

    static var supabaseAnonKey: String {
        guard
            let key = Bundle.main.object(forInfoDictionaryKey: "SUPABASE_ANON_KEY") as? String,
            !key.isEmpty
        else {
            fatalError("SUPABASE_ANON_KEY is missing. Check Echo/Resources/Secrets.xcconfig.")
        }
        return key
    }


    /// Where anonymous feedback is posted, and the token sent with it.
    ///
    /// Both live in Secrets.xcconfig rather than in source because this repo is
    /// public: an endpoint in a binary takes effort to extract, whereas one in a
    /// public repo is scraped by bots within minutes of the push.
    ///
    /// Only the deployment id is stored — an xcconfig reads an unescaped `//` as
    /// the start of a comment, so a full URL arrives as `https:`. The `$()`
    /// escape does not survive the round trip through the generated plist
    /// either, so the URL is assembled here instead, exactly as the Supabase
    /// URL is built from its project ref.
    ///
    /// Optional rather than `fatalError`: a missing feedback destination should
    /// disable one screen, never stop the app launching.
    static var feedbackEndpoint: URL? {
        guard
            let id = Bundle.main.object(forInfoDictionaryKey: "FEEDBACK_SCRIPT_ID") as? String,
            !id.isEmpty
        else { return nil }
        return URL(string: "https://script.google.com/macros/s/\(id)/exec")
    }

    static var feedbackSecret: String {
        Bundle.main.object(forInfoDictionaryKey: "FEEDBACK_SECRET") as? String ?? ""
    }

    // API_HOST is deliberately gone. Summaries are generated by calling
    // Anthropic directly from the device with the user's own key — see
    // `AnthropicClient` — so the app depends on no server of ours at all.
}
